name: Build and Run Docker Container

on:
  push:
    branches:
      - main  # Ubah sesuai dengan nama branch yang ingin Anda monitor
  pull_request:
    branches:
      - main  # Ubah sesuai dengan nama branch yang ingin Anda monitor

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: chriskm12
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Build Docker image
      run: |
        echo run build
        #docker build . -t chriskm12/sad:1010
    - name: push docker
      run: |
        echo run push
        #docker push chriskm12/sad:1010

    - name: Run Docker container
      run: docker run -d -p 8080:8080 --name my-python-app chriskm12/sad:1010

    - name: Wait for the container to start
      run: |
        for i in {1..10}; do
          if [ "$(docker inspect -f {{.State.Running}} my-python-app)" == "true" ]; then
            echo "Container is running"
            exit 0
          fi
          echo "Waiting for container to start..."
          sleep 5
        done
        echo "Container did not start in time"
        docker logs my-python-app
        exit 1
    - name: Display Docker container logs
      if: always()
      run: docker logs my-python-app
    - run: |
        ls
